use Mix.Config
import_config "prod.exs"

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :phoenix_codedeploy, PhoenixCodedeploy.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "red-example.com"],
  cache_static_manifest: "priv/static/manifest.json"

# Use test gateway for stripe in QA
config :phoenix_codedeploy, :stripe,
 token: "sk_test_QwrSPonmUQuMLs7KvLTgfhY"

# Override recipients so we don't spam actual accounts
# with test emails
config :phoenix_codedeploy, :email,
  contact_to: "qa-team@example.com"
